Module4 task1
htmlacademy-react/13228-what-to-watch-7 pull request #6
Opened 2021-06-19 11:45 UTC by lordoys

2021-06-20 08:12 UTC, quasko commented
Ошибки линтера:
![image](https://user-images.githubusercontent.com/5688555/122666835-524e8f80-d1b8-11eb-8bf0-202eee0e17ef.png)

2021-06-20 08:32 UTC, quasko commented
при наведении курсора на карточку фильма в консоль падает ошибка
![image](https://user-images.githubusercontent.com/5688555/122667352-1b2dad80-d1bb-11eb-88b1-c9b77f7fac37.png)
и видео не воспроизводится

2021-06-20 08:33 UTC, quasko commented
При обновлении главной страницы пытаются загрузится сразу все видео, что приводит к ошибке множественных запросов
![image](https://user-images.githubusercontent.com/5688555/122667374-3ef0f380-d1bb-11eb-82f5-7464124f5d6b.png)
Нужно предусмотреть что бы видео загружалось только после наведения курсора

2021-06-20 08:55 UTC, quasko requested changes

2021-06-20 08:55 UTC, quasko commented on project/src/components/add-review-page/add-review-page.jsx
> +                <Link className="breadcrumbs__link">Add review</Link>
у компонента Link есть обязательный пропс `to`

2021-06-20 08:55 UTC, quasko commented on project/src/components/film-card/film-card.jsx
> +    <article ref={cardRef} onMouseLeave={handleMouseLeave} onMouseEnter={handleMouseEnter} className="small-film-card catalog__films-card">
сardRef нужен для управления элементом video, тогда логичней его привязать именно к тегу видео и не нужно будет ходить по DOM и использовать конструкции `.current.firstChild.`

2021-06-20 08:55 UTC, quasko commented on project/src/components/film-card/film-card.jsx
> +    cardRef.current.firstChild.load();
load приводит к повторной загрузке видеофайла
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/load
можно использовать метод play + сброс currentTime
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/currentTime

2021-06-20 08:55 UTC, quasko commented on project/src/components/film-video/film-video.jsx
> +  return <video  muted poster={poster} src={src} width="280" height="175"/>;
размеры лучше вынести в конфиг

2021-06-20 08:55 UTC, quasko commented on project/src/components/film-card/film-card.jsx
> +  let cardIsHovered = false;
вместо отдельной переменной cardIsHovered лучше использовать таймер, который можно задавать по mouseEnter, а сбрасывать (clearTimeout) по mouseLeave.

2021-06-20 08:59 UTC, quasko commented
https://github.com/lordoys/13228-what-to-watch-7/blob/e367beba007eb0ef19e73465d02dbb41d90bc367/project/src/components/player-page/player-page.jsx#L7

прошлый раз не поправил одно замечание
![image](https://user-images.githubusercontent.com/5688555/122668051-fc311a80-d1be-11eb-8826-7022f0270cbc.png)

2021-06-20 10:05 UTC, lordoys commented on project/src/components/film-card/film-card.jsx
> +    <article ref={cardRef} onMouseLeave={handleMouseLeave} onMouseEnter={handleMouseEnter} className="small-film-card catalog__films-card">
Изначально так и сделал, но выводит ошибку о том, что нельзя применять ref к функциональным компонентам.

2021-06-21 18:15 UTC, quasko commented on project/src/components/film-card/film-card.jsx
> +    <article ref={cardRef} onMouseLeave={handleMouseLeave} onMouseEnter={handleMouseEnter} className="small-film-card catalog__films-card">
если нужно прокинуть ref через пропсы, то можно использовать [forwardRef](https://ru.reactjs.org/docs/forwarding-refs.html)

2021-06-21 18:23 UTC, quasko commented
Не все замечания исправлены:
1) video отменить preload
2) reduce -> find
3) forwardRef

2021-06-22 09:04 UTC, merged